name: Spark 3.4 / Java 17 / Scala 2.13
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java, SBT
        uses: olafurpg/setup-scala@v11
        with:
          java-version: 'openjdk@1.17.0'
      - name: Build and test
        run: sbt -Dspark.testVersion=3.4.1 ++2.13.8 clean scalastyle test:scalastyle mimaReportBinaryIssues test
