name: Spark 3 / Java 8 / Scala 2.12
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java, SBT
        uses: olafurpg/setup-scala@v11
        with:
          java-version: 'adopt@1.8'
      - name: Build and test
        run: sbt -Dspark.testVersion=3.0.3 ++2.12.10 clean scalastyle test:scalastyle mimaReportBinaryIssues coverage test coverageReport
      - name: Check code coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
